# Generated by Django 5.2.2 on 2025-06-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('skills', models.TextField(blank=True)),
                ('experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=10)),
                ('responsibilities', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20)),
                ('additional', models.TextField(blank=True)),
                ('skills_priority', models.IntegerField(default=0)),
                ('experience_priority', models.IntegerField(default=0)),
                ('education_priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
